export const CREATED_STATUS = 201;
export const INVALID_REQUEST_STATUS = 400;
export const INTERNAL_SERVER_ERROR_STATUS = 500;

export default {
  CREATED_STATUS,
  INVALID_REQUEST_STATUS,
  INTERNAL_SERVER_ERROR_STATUS,
};
